version: '3.3'
services: 
    web:
        build: .
        container_name: php
        ports:
            - 80:80
        env_file:
            - .env
        restart: always
        depends_on: 
            - mysql-server
        networks:
            - database  
    mysql-server:
        image: mysql:latest
        container_name: mysql-server
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - volumedb:/var/lib/mysql
        ports:
            - "3308:3306" #mysql running on host's port 3308
        networks:
            - database     
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        environment:
            PMA_ARBITRARY: 1
            # PMA_HOST: mysql-server
            # PMA_USER: "${DB_USERNAME}"
            # PMA_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "8001:80" #PMA running on host's port 8001
        depends_on: 
            - mysql-server
        networks:
            - database    
volumes: 
    volumedb:   
networks:
    database: